//! JSON Schema helper functions to suppress non-standard `format` keywords
//! generated by schemars for unsigned integer types.

use schemars::{json_schema, Schema, SchemaGenerator};

/// Schema for unsigned integer fields without the non-standard `format` keyword.
/// Emits `{"type": "integer", "minimum": 0}`.
pub fn uint_schema(_gen: &mut SchemaGenerator) -> Schema {
    json_schema!({
        "type": "integer",
        "minimum": 0
    })
}

/// Schema for `Option<usize>`/`Option<u32>`/`Option<u64>` without the
/// non-standard `format` keyword.
/// Emits `{"anyOf": [{"type": "null"}, {"type": "integer", "minimum": 0}]}`.
pub fn option_uint_schema(_gen: &mut SchemaGenerator) -> Schema {
    json_schema!({
        "anyOf": [
            {"type": "null"},
            {"type": "integer", "minimum": 0}
        ]
    })
}
